"""Basic UI components for the new Specter DIY clean interface."""
from .ui_consts import (
    BTN_HEIGHT, BTN_WIDTH, BACK_BTN_HEIGHT, BACK_BTN_WIDTH,
    SCREEN_WIDTH, SCREEN_HEIGHT,
    MENU_PCT, PAD_SIZE,
    TITLE_ROW_HEIGHT, TITLE_PADDING,
    MODAL_WIDTH_PCT, MODAL_HEIGHT_PCT,
    EXPLAINER_WIDTH_PCT, EXPLAINER_HEIGHT_PCT, EXPLAINER_OVERLAY_OPA,
    SWITCH_HEIGHT, SWITCH_WIDTH,
    STATUS_BTN_HEIGHT, STATUS_BTN_WIDTH, STATUS_BAR_PCT, CONTENT_PCT,
    PIN_BTN_WIDTH, PIN_BTN_HEIGHT,
    BTC_ICON_WIDTH, BTC_ICON_ZOOM,
    MENU_TITLE_FONT_SIZE, MENU_ITEM_FONT_SIZE,
    ONE_LETTER_SYMBOL_WIDTH, TWO_LETTER_SYMBOL_WIDTH, THREE_LETTER_SYMBOL_WIDTH,
    GREEN, ORANGE, RED, WHITE, GREY, BLACK,
    GREEN_HEX, ORANGE_HEX, RED_HEX, WHITE_HEX, GREY_HEX, BLACK_HEX,
    CYAN, CYAN_HEX, CYAN_DARK, CYAN_DARK_HEX,
    BG_BLACK_HEX, BG_DARK_HEX, BG_CARD_HEX, BG_ELEVATED_HEX,
    TOP_BAR_HEIGHT, SEED_DROPDOWN_HEIGHT, WALLET_SECTION_HEIGHT, NAV_BAR_HEIGHT,
)
from .modal_overlay import ModalOverlay
from .symbol_lib import BTC_ICONS
from .specter_gui import SpecterGui

__all__ = [
    "BTN_HEIGHT", "BTN_WIDTH", "BACK_BTN_HEIGHT", "BACK_BTN_WIDTH",
    "SCREEN_WIDTH", "SCREEN_HEIGHT",
    "MENU_PCT", "PAD_SIZE",
    "SWITCH_HEIGHT", "SWITCH_WIDTH",
    "STATUS_BTN_HEIGHT", "STATUS_BTN_WIDTH", "STATUS_BAR_PCT", "CONTENT_PCT",
    "PIN_BTN_WIDTH", "PIN_BTN_HEIGHT",
    "BTC_ICON_WIDTH", "BTC_ICON_ZOOM",
    "MENU_TITLE_FONT_SIZE", "MENU_ITEM_FONT_SIZE",
    "ONE_LETTER_SYMBOL_WIDTH", "TWO_LETTER_SYMBOL_WIDTH", "THREE_LETTER_SYMBOL_WIDTH",
    "GREEN", "ORANGE", "RED", "WHITE", "GREY", "BLACK",
    "GREEN_HEX", "ORANGE_HEX", "RED_HEX", "WHITE_HEX", "GREY_HEX", "BLACK_HEX",
    "CYAN", "CYAN_HEX",
    "BG_BLACK_HEX", "BG_DARK_HEX", "BG_CARD_HEX",
    "ModalOverlay", "BTC_ICONS", "SpecterGui",
]
